# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 04:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_snapshot', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('finish_reason', models.CharField(choices=[('not_finished', 'Not Finished'), ('dialog_concluded', 'Dialog Concluded'), ('user_cancelled', 'User Cancelled'), ('dialog_cancelled', 'Dialog Cancelled'), ('timed_out', 'Timed Out')], default='not_finished', max_length=128)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DialogScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DialogStateTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('state_id', models.CharField(max_length=128)),
                ('prior_state_id', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('dialog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='django_dialog_engine.Dialog')),
            ],
        ),
        migrations.AddField(
            model_name='dialog',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogs', to='django_dialog_engine.DialogScript'),
        ),
    ]
