# pylint: skip-file

# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogscript',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dialogscript',
            name='name',
            field=models.CharField(default='New Dialog Script', max_length=1024),
        ),
    ]
