# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0002_auto_20180214_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogs', to='django_dialog_engine.DialogScript'),
        ),
    ]
