# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0003_auto_20190218_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
