# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-05 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0004_dialog_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogstatetransition',
            name='refresh',
            field=models.BooleanField(default=True),
        ),
    ]
