# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0005_dialogstatetransition_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogstatetransition',
            name='refresh',
            field=models.BooleanField(default=False),
        ),
    ]
