# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0006_auto_20191205_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogstatetransition',
            name='refresh',
        ),
    ]
