# pylint: skip-file
# Generated by Django 3.2.4 on 2021-06-14 20:06

from django.db import migrations, models
from django.utils import version

class Migration(migrations.Migration):
    dependencies = [
        ('django_dialog_engine', '0008_dialogscript_identifier'),
    ]

    if version.get_complete_version()[0] >= 3:
        operations = [
            migrations.AlterField(
                model_name='dialog',
                name='dialog_snapshot',
                field=models.JSONField(blank=True, null=True),
            ),
            migrations.AlterField(
                model_name='dialog',
                name='id',
                field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            ),
            migrations.AlterField(
                model_name='dialog',
                name='metadata',
                field=models.JSONField(default=dict),
            ),
            migrations.AlterField(
                model_name='dialogscript',
                name='definition',
                field=models.JSONField(blank=True, null=True),
            ),
            migrations.AlterField(
                model_name='dialogscript',
                name='id',
                field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            ),
            migrations.AlterField(
                model_name='dialogstatetransition',
                name='id',
                field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            ),
            migrations.AlterField(
                model_name='dialogstatetransition',
                name='metadata',
                field=models.JSONField(default=dict),
            ),
        ]
    else:
        operations = []
