# pylint: skip-file
# Generated by Django 3.2.10 on 2021-12-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0009_auto_20210614_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='finish_reason',
            field=models.CharField(choices=[('not_finished', 'Not Finished'), ('dialog_concluded', 'Dialog Concluded'), ('user_cancelled', 'User Cancelled'), ('dialog_cancelled', 'Dialog Cancelled'), ('dialog_error', 'Dialog Error'), ('timed_out', 'Timed Out')], default='not_finished', max_length=128),
        ),
    ]
