# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-01 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0010_alter_dialog_finish_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogscript',
            name='labels',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),
    ]
