# pylint: skip-file
# Generated by Django 3.2.18 on 2023-03-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0012_dialogscript_embeddable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogstatetransition',
            name='when',
            field=models.DateTimeField(db_index=True),
        ),
    ]
