# pylint: skip-file
# Generated by Django 3.2.18 on 2023-03-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0013_alter_dialogstatetransition_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogstatetransition',
            name='prior_state_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dialogstatetransition',
            name='state_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
