# pylint: skip-file
# Generated by Django 3.2.24 on 2024-04-18 12:44

from django.db import migrations, models
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0014_auto_20230327_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogscript',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DialogScriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Dialog Script', max_length=1024)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('embeddable', models.BooleanField(default=False)),
                ('identifier', models.SlugField(blank=True, max_length=1024, null=True)),
                ('labels', models.TextField(blank=True, max_length=1048576, null=True)),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('dialog_script', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='django_dialog_engine.dialogscript')),
            ],
        ),
    ]
