# pylint: skip-file
# Generated by Django 3.2.24 on 2024-04-18 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_dialog_engine', '0015_auto_20240418_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogscriptversion',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
