# pylint: skip-file
# Generated by Django 4.2.11 on 2024-04-26 18:40

from django.db import migrations
import django.contrib.postgres.fields.jsonb

class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0016_dialogscriptversion_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogscriptversion',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='dialogscriptversion',
            name='definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
