# pylint: skip-file
# Generated by Django 3.2.25 on 2024-05-02 20:11

from django.db import migrations
import django.contrib.postgres.fields.jsonb

class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0017_alter_dialogscriptversion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogscriptversion',
            name='definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
