# pylint: skip-file
# Generated by Django 4.2.13 on 2024-06-21 18:49

import sys

from django.db import migrations, models

if sys.version_info[0] > 2:
    from django.db.models import JSONField # pylint: disable=no-name-in-module
else:
    from django.contrib.postgres.fields import JSONField

class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0018_alter_dialogscriptversion_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogscriptversion',
            name='definition',
            field=JSONField(blank=True, null=True),
        ),
    ]
