# pylint: skip-file
# Generated by Django 5.2.16 on 2026-07-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine', '0019_alter_dialogscriptversion_definition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogscript',
            options={'ordering': ['name']},
        ),
    ]
